<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <StartupObject>QRCodeAutomation.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="generate\**" />
    <Compile Remove="read\**" />
    <None Include="generate\**" />
    <None Include="read\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.12" />
  </ItemGroup>

</Project>
